- name: Restart ssh
  systemd:
    name: ssh
    state: restarted

- name: Restart iptables
  systemd:
    name: iptables
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Restart ntp
  systemd:
    name: ntp
    state: restarted

- name: Restart auditd
  command: systemctl restart auditd

- name: Generate auditd
  command: augenrules

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Update cracklib debian
  command: update-cracklib
