---
dns_v4: 1.1.1.3
dns_v4_fallback: 1.0.0.3
dns_v6: 2606:4700:4700::1113
dns_v6_fallback: 2606:4700:4700::1003

domain: "{{ lookup('env', 'DOMAIN') | default('')  }}"
email: "{{ lookup('env', 'CLOUDFLARE_EMAIL') | default('')  }}"
is_domain_defined: "{{ domain is defined and domain != '' }}"

xui_port: 2053
xui_username: "{{ lookup('env', 'XUI_USERNAME') | default('admin') }}"
xui_password: "{{ lookup('env', 'XUI_PASSWORD') | default('admin') }}"
xui_web_path: /
