---
- name: install basic tools
  apt:
    update_cache: yes
    name:
      - curl
      - wget
      - vim
      - htop
      - iptables-persistent
      - sqlite3
      - gnupg2 
      - ca-certificates 
      - lsb-release 
    state: present

- name: set dns servers
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
