---
- name: Configure resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root

- name: Copy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
