---
- name: Remove netfilter blacklist if exists
  file:
    path: /etc/modprobe.d/disable-netfilter.conf
    state: absent

- name: Install iptables
  apt:
    update_cache: true
    name: iptables-persistent
    state: present

- name: Enable iptables service
  systemd:
    name: iptables
    enabled: true
    state: started
  ignore_errors: true

- name: Make iptables configuration file
  template:
    src: iptables.j2
    dest: /etc/iptables/rules.v4
  tags: iptables

- name: Restore iptables state
  shell: iptables-restore < /etc/iptables/rules.v4
  async: 45
  poll: 15
  ignore_errors: true
  tags: iptables
