---
- name: Configure GRUB
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet audit=0 mitigations=off"'

- name: Update GRUB configuration
  command: update-grub

- name: Reboot the server
  reboot:
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
