---
- name: Disable systemd-journald logging
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#Storage='
    line: 'Storage=none'
    state: present
  ignore_errors: true

- name: Disable systemd-journald service
  systemd:
    name: systemd-journald
    masked: true
    enabled: false
    state: stopped
  ignore_errors: true

- name: Disable rsyslog service
  systemd:
    name: rsyslog
    state: stopped
    masked: true
    enabled: false
  ignore_errors: true

- name: Disable logrotate service
  systemd:
    name: logrotate
    state: stopped
    masked: true
    enabled: false
  ignore_errors: true

- name: Disable auditd service
  systemd:
    name: auditd
    state: stopped
    masked: true
    enabled: false
  ignore_errors: true

- name: Remove cron daily logrotate
  file:
    path: /etc/cron.daily/logrotate
    state: absent
  ignore_errors: true
