---
- name: Install packages
  import_tasks: packages.yml
  tags: packages

- name: Configure monitoring
  import_tasks: monitoring.yml
  tags: monitoring
  when: monitoring

- name: Configure systemd services
  import_tasks: systemd.yml
  tags: systemd

- name: Configure limits
  import_tasks: limits.yml
  tags: limits

- name: Configure sshd
  import_tasks: sshd.yml
  tags: sshd

- name: Confiugre DNS
  import_tasks: dns.yml
  tags: dns

- name: Configure network interfaces
  import_tasks: nic.yml
  tags: nic

- name: Disable the netfilter
  import_tasks: netfilter.yml
  tags: disable-netfilter
  when: firewall == 'none'

- name: Configure nftables
  import_tasks: nftables.yml
  tags: firewall
  when: firewall == 'nftables'

- name: Configure sysctl settings
  import_tasks: sysctl.yml
  tags: sysctl

- name: Install samurai kernel
  import_tasks: samurai.yml
  tags: samurai
  when: samurai

- name: Configure kernel
  import_tasks: kernel.yml
  tags: kernel
