---
- name: Install packages
  import_tasks: packages.yml
  tags: packages

- name: Configure monitoring
  import_tasks: monitoring.yml
  tags: monitoring
  when: monitoring

- name: Configure logging
  import_tasks: logging.yml
  tags: logging

- name: Change limits.conf
  import_tasks: limits.yml
  tags: limits

- name: Configure sshd
  import_tasks: hardening.yml
  tags: hardening

- name: Confiugre DNS
  import_tasks: dns.yml
  tags: dns

- name: Configure network interfaces
  import_tasks: nic.yml
  tags: nic

- name: Disable the netfilter
  import_tasks: netfilter.yml
  tags: disable-netfilter
  when: firewall == 'none'

- name: Configure nftables
  import_tasks: nftables.yml
  tags: nftables
  when: firewall == 'nftables'

- name: Disable and stop unnecessary services
  import_tasks: services.yml
  tags: services

- name: Apply sysctl settings
  import_tasks: sysctl.yml
  tags: sysctl

- name: Samurai kernel
  import_tasks: samurai.yml
  tags: samurai
  when: samurai

- name: Configure kernel
  import_tasks: kernel.yml
  tags: kernel
