---
- name: Remove netfilter blacklist if exists
  file:
    path: /etc/modprobe.d/disable-netfilter.conf
    state: absent

- name: Install nftables
  apt:
    update_cache: true
    name: nftables
    state: present

- name: Enable nftables service
  systemd:
    name: nftables
    enabled: true
    state: started
  ignore_errors: true

- name: Make nftables configuration file
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
  tags: nftables

- name: Restore nftables state
  shell: nft -f /etc/nftables.conf
  async: 45
  poll: 15
  ignore_errors: true
  tags: nftables
