---
- name: Update repositories
  apt:
    update_cache: true
    upgrade: false
    cache_valid_time: 86400

- name: Install basic tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
