---
- name: install 3x-ui panel
  shell: |
    if ! command -v x-ui &> /dev/null; then
      yes n | bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh)
    fi
  args:
    executable: /bin/bash

- name: enable and start 3x-ui panel
  systemd:
    name: x-ui
    enabled: yes
    state: started

- name: configure 3x-ui panel
  shell: |
    /usr/local/x-ui/x-ui setting -port {{ xui_port }} -username {{ xui_username }} -password {{ xui_password }} -webBasePath {{ xui_web_path  }} && /usr/local/x-ui/x-ui migrate
  args:
    executable: /bin/bash
  notify: 
    - restart x-ui

- name: check if inbound already exists
  shell: |
    sqlite3 /etc/x-ui/x-ui.db "SELECT COUNT(*) FROM inbounds WHERE id = 1;"
  args:
    executable: /bin/bash
  register: inbound_check

- name: add inbound if not already present
  script: files/inbound.sh
  args:
    executable: /bin/bash
  when: inbound_check.stdout is defined and inbound_check.stdout | trim == "0" 
  register: inbound_output
  changed_when: inbound_output.rc == 0
  environment:
    DOMAIN: "{{ domain }}"
  notify:
    - restart x-ui

- name: apply routing settings
  script: files/settings.sh
  args:
    executable: /bin/bash
  notify: 
    - restart x-ui
