---
- name: Preparing tasks for every playbooks
  import_playbook: preparing.yml

- name: Install NGINX
  hosts: all
  become: true
  roles:
    - { role: ../roles/nginx, tags: nginx, when: enable_nginx and is_domain_defined }

- name: Install 3x-UI
  hosts: all
  become: true
  roles:
    - { role: ../roles/xui, tags: xui, when: enable_xui }
