---
## NIC configuration
##
## https://www.kernel.org/doc/Documentation/networking/segmentation-offloads.txt
## https://en.wikipedia.org/wiki/TCP_offload_engine
##
tso: "on"
gso: "on"
gro: "on"
lro: "on"
highdma: "on"
rx_gro_hw: "on"
rx_gro_list: "on"
tx_gso_robust: "on"
rx_checksumming: "on"
tx_checksumming: "on"
tx_nocache_copy: "on"
receive_hashing: "on"
scatter_gather: "on"
rx_udp_gro_forwarding: "on"
tx_udp_tnl_segmentation: "on"
tx_udp_tnl_csum_segmentation: "on"

## Ethernet flow control
## https://en.wikipedia.org/wiki/Ethernet_flow_control
autoneg: "on"
rx: "on"
tx: "on"

## Adaptive RX/TX
adaptive_rx: "on"
adaptive_tx: "on"

## RX/TX polling interval
rx_usecs: 256
tx_usecs: 0

## RX/TX polling queue length
rx_frames: 16
tx_frames: 1

## NAPI
napi_defer_hard_irqs: 1
gro_flush_timeout: 1
threaded_napi: 1

## RPS & RFS
## https://docs.kernel.org/networking/scaling.html
## https://www.suse.com/de-de/support/kb/doc/?id=000018430
## https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/6/html/performance_tuning_guide/network-rps#network-rps
rps: false
