# basic package list for installation
packages:
- wget
- git
- vim
- bash-completion
- curl
- htop
- iftop
- ca-certificates
- sqlite3
- jq
- ncdu
- unzip
- net-tools
- dnsutils
- sudo
#- ntp
- fail2ban
- software-properties-common
- apache2-utils
- tcpdump
- telnet
- axel
- iptables-persistent
- auditd
- libpwquality-common
- cracklib-runtime
- python3-requests
- debian-archive-keyring
- certbot
- python3-certbot-nginx

# sshd configuration
sshd_config:
  Port: "{{ ansible_port }}"
  ListenAddress: 0.0.0.0
  PermitRootLogin: without-password
  PasswordAuthentication: "no"
  AllowUsers: root
  AllowGroups: root

# iptables configuration
iptables:
  network_adapter_access:
    - lo
  tcp_port_access:
    - 80
    - 443
    - 2086
    - 2087
  #udp_port_access:
  #trusted_range:

# fail2ban configuration
fail2ban:
  bantime: 10m
  findtime: 10m
  maxretry: 5

# session timeout setting (seconds)
timeout_time: 600

# auditd vars
auditd_apply_audit_rules: yes
auditd_action_mail_acct: root
auditd_admin_space_left_action: suspend
auditd_disk_error_action: suspend
auditd_disk_full_action: suspend
auditd_max_log_file: 8
auditd_max_log_file_action: keep_logs
auditd_mode: 1
auditd_num_logs: 5
auditd_space_left: 75
auditd_space_left_action: email
grub_audit_backlog_cmdline: audit_backlog_limit=8192
grub_audit_cmdline: audit=1

# resolv.conf name servers
dns_v4: 1.1.1.3
dns_v4_fallback: 1.0.0.3
dns_v6: 2606:4700:4700::1113
dns_v6_fallback: 2606:4700:4700::1003

# dns variables for systemd-resolved
dns: 1.1.1.3
fallback_dns: 1.0.0.3
dnssec: allow-downgrade
dns_over_tls: opportunistic

# limit.conf variables
limit_nofile_hard: 1000000
limit_nofile_soft: 1000000
limit_nproc_hard: 10000
limit_nproc_soft: 10000

# sysctll configuration variables
sysctl_config:
  net.core.somaxconn: 8192
  net.ipv4.tcp_fin_timeout: 10
  net.ipv4.tcp_keepalive_time: 120
  net.ipv4.tcp_ecn: 1
  net.ipv4.tcp_keepalive_intvl: 20
  net.ipv4.tcp_keepalive_probes: 3
  net.ipv4.tcp_sack: 1
  net.ipv4.tcp_window_scaling: 1
  net.ipv4.tcp_mtu_probing: 1
  net.ipv4.tcp_max_syn_backlog: 1024
  net.ipv4.tcp_rmem: "8192 87380 16777216"
  net.ipv4.tcp_wmem: "8192 65536 16777216"
  net.ipv4.tcp_low_latency: 1
  net.ipv4.tcp_fastopen: 3
  net.core.rmem_default: 262144
  net.core.wmem_default: 262144
  net.core.rmem_max: 16777216
  net.core.wmem_max: 16777216
  net.core.netdev_max_backlog: 65535
  net.core.optmem_max: 131072
  net.unix.max_dgram_qlen: 65535
  net.ipv4.udp_rmem_min: 8192
  net.ipv4.udp_wmem_min: 8192
  net.ipv4.udp_l3mdev_accept: 1
  net.ipv4.ip_default_ttl: 64
  net.core.default_qdisc: fq
  net.ipv4.tcp_congestion_control: bbr
  net.ipv4.icmp_echo_ignore_all: 0
  net.ipv4.ip_forward: 1
  net.ipv4.conf.all.forwarding: 1
  net.ipv6.conf.all.forwarding: 1
  vm.max_map_count: 262144
  fs.file-max: 1500000
  net.ipv4.tcp_tw_reuse: 1
  net.netfilter.nf_conntrack_tcp_timeout_established: 900
  net.netfilter.nf_conntrack_tcp_timeout_close_wait: 10
  net.netfilter.nf_conntrack_tcp_timeout_syn_recv: 30
  net.netfilter.nf_conntrack_max: 262144
  net.ipv4.tcp_syncookies: 1
  net.ipv4.conf.default.rp_filter: 1
  net.ipv4.conf.all.rp_filter: 1
