## config dir path
config_dir: /opt/nova

## basic package list for installation
packages:
- vim
- bash-completion
- curl
- ca-certificates
- unzip
- net-tools
- dnsutils
- tcpdump
- ethtool

## monitoring (prometheus)
monitoring: false
node_exporter_listen_address: ":10100"

## sshd configuration
sshd_config:
  Port: "{{ ansible_port }}"
  ListenAddress: 0.0.0.0
  PermitRootLogin: without-password
  PasswordAuthentication: "no"
  AllowUsers: root
  AllowGroups: root

## firewall system
## supported: nftables, iptables, none
firewall: nftables

## firewall configuration
firewall_config:
  network_adapter_access:
    - lo
  tcp_port_access:
    - 80
    - 443
    - 2087
    - 8080
  # udp_port_access:
  #   - 8082
  #   - 8084
  # trusted_range:
  #   - 1.1.1.1/24

## ToS configuration
## https://en.wikipedia.org/wiki/Type_of_service
tos: true
tcp_tos: "0x28"
udp_tos: "0x00"

## resolv.conf name servers
dns: 1.1.1.3
dns_fallback: 1.0.0.3
dns_v6: 2606:4700:4700::1113
dns_v6_fallback: 2606:4700:4700::1003

## limit.conf variables
limit_nofile_hard: 1000000
limit_nofile_soft: 1000000
limit_nproc_hard: 10000
limit_nproc_soft: 10000

## qdisc configuration
_fq_codel: "fq_codel target 5ms interval 100ms noecn limit 10240 flows 1024 quantum 1514"
_fq: "fq quantum 1514 initial_quantum 15140 flow_limit 1024 limit 10240 buckets 8192"
_txqueuelen: 1000

## supported qdisc: noqueue, fq_codel, fq
qdisc: fq

## NIC configuration
##
## https://www.kernel.org/doc/Documentation/networking/segmentation-offloads.txt
## https://en.wikipedia.org/wiki/TCP_offload_engine
##
tso: "on"   # TCP Segmentation Offload
gso: "on"   # Generic Segmentation Offload
gro: "on"   # Generic Receive Offload
lro: "off"   # Large Receive Offload

## Ethernet flow control
## https://en.wikipedia.org/wiki/Ethernet_flow_control
autoneg: "off"
rx: "off"
tx: "off"

## Adaptive RX/TX
adaptive_rx: "on"
adaptive_tx: "on"

## RX/TX polling interval
rx_usecs: 0
tx_usecs: 0

## RX/TX queue length
rx_frames: 1
tx_frames: 1

## NAPI
napi_defer_hard_irqs: 1
gro_flush_timeout: 1
threaded_napi: 1

## sysctl configuration variables
sysctl_config:
  net.core.default_qdisc: fq
  net.core.somaxconn: 4096
  net.core.netdev_max_backlog: 50000
  net.unix.max_dgram_qlen: 4096
  net.core.busy_read: 5000
  net.core.busy_poll: 5000
  net.core.netdev_budget: 600
  net.core.netdev_budget_usecs: 400
  net.core.dev_weight: 64
  net.core.dev_weight_rx_bias: 1
  net.core.dev_weight_tx_bias: 1
  net.core.flow_limit_table_len: 4096
  net.core.flow_limit_cpu_bitmap: 0
  net.core.netdev_tstamp_prequeue: 0
  net.core.rmem_default: 1048576
  net.core.wmem_default: 1048576
  net.core.rmem_max: 16777216
  net.core.wmem_max: 16777216
  net.core.optmem_max: 65536
  net.ipv4.tcp_no_metrics_save: 1
  net.ipv4.tcp_fin_timeout: 1
  net.ipv4.tcp_keepalive_time: 120
  net.ipv4.tcp_ecn: 1
  net.ipv4.tcp_sack: 1
  net.ipv4.tcp_mtu_probing: 1
  net.ipv4.tcp_timestamps: 1
  net.ipv4.tcp_keepalive_intvl: 20
  net.ipv4.tcp_keepalive_probes: 3
  net.ipv4.tcp_max_orphans: 524288
  net.ipv4.tcp_retries2: 3
  net.ipv4.tcp_synack_retries: 2
  net.ipv4.tcp_window_scaling: 1
  net.ipv4.tcp_slow_start_after_idle: 0
  net.ipv4.tcp_max_tw_buckets: 262144
  net.ipv4.tcp_syncookies: 1
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_max_syn_backlog: 4096
  net.ipv4.tcp_rmem: "4096 87380 16777216"
  net.ipv4.tcp_wmem: "4096 16384 16777216"
  net.ipv4.tcp_limit_output_bytes: 131072
  net.ipv4.tcp_low_latency: 0
  net.ipv4.tcp_fastopen: 3
  net.ipv4.tcp_congestion_control: bbr
  net.ipv4.udp_rmem_min: 1048576
  net.ipv4.udp_wmem_min: 1048576
  net.ipv4.udp_l3mdev_accept: 1
  net.ipv4.ip_default_ttl: 64
  net.ipv4.ip_early_demux: 1
  net.ipv4.ip_forward: 1
  net.ipv4.conf.all.forwarding: 1
  net.ipv6.conf.all.forwarding: 1
  net.ipv4.conf.default.rp_filter: 0
  net.ipv4.conf.all.rp_filter: 0
  net.ipv4.icmp_echo_ignore_all: 1
  fs.file-max: 2097152
  vm.max_map_count: 262144
  vm.swappiness: 0
  vm.dirty_ratio: 5
  vm.dirty_background_ratio: 5
  vm.compaction_proactiveness: 0
  kernel.printk: "0 4 1 3"
  kernel.randomize_va_space: 0
  kernel.numa_balancing: 0
  kernel.watchdog_thresh: 30
  kernel.sched_rt_period_us: 1000000
  kernel.sched_rt_runtime_us: 950000
  kernel.perf_event_max_sample_rate: 100
  kernel.core_pattern: "/dev/null"
