---
- name: Install Web packages
  apt:
    update_cache: yes
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
      - python3-requests
    state: present

- name: Enable and start NGINX
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy NGINX config
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  tags: nginx

- name: Check certs directory
  stat:
    path: /etc/letsencrypt/live/{{ domain }}/
  register: certs_file

- name: Getting TLS certificates
  shell: |
    systemctl stop nginx
    certbot certonly --standalone --preferred-challenges http -d {{ domain }} --non-interactive --agree-tos -m {{ email }}
    systemctl start nginx
  changed_when: false
  when: not certs_file.stat.exists
  
- name: Deploy Nova NGINX config
  template:
    src: templates/nova.conf.j2
    dest: /etc/nginx/conf.d/{{ domain }}.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload nginx
  tags: nginx
