---
- hosts: all
  become: yes
  vars:
    domain: "{{ lookup('env', 'DOMAIN') | default('')  }}"
    subdomain: "{{ lookup('env', 'SUBDOMAIN') | default('')  }}"
    email: "{{ lookup('env', 'CLOUDFLARE_EMAIL') | default('')  }}"
  roles:
    - xui

